1_Data_Prep

In [28]:
import pandas as pd
import numpy as np

df_historico = pd.read_csv('../data/raw/All_Players_1992-2025.csv')
df_historico.head()

,PlayerID,Player,Squad,League,Nation,Pos,Age,Born,Season,MP,...,The Best FIFA Mens Player,UEFA Best Player,UCL_MP,UCL_Gls,UCL_xG,UCL_Ast,UCL_xA,UCL_KP,UCL_GCA,UCL_SCA
0,4,Alexander Strehmel,Stuttgart,Bundesliga,GER,"DF,MF",24.0,1968.0,1992-1993,20.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,4,Alexander Strehmel,Stuttgart,Bundesliga,GER,"DF,MF",25.0,1968.0,1993-1994,13.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4,Alexander Strehmel,Unterhaching,Bundesliga,GER,"DF,MF",31.0,1968.0,1999-2000,25.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,Alexander Strehmel,Unterhaching,Bundesliga,GER,"DF,MF",32.0,1968.0,2000-2001,32.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,6,Alois Reinhardt,Bayern Munich,Bundesliga,GER,DF,30.0,1961.0,1992-1993,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [29]:
df_actual = pd.read_csv('../data/raw/Season_2025-2026.csv')
df_actual.head()

,PlayerID,Player,Squad,League,Nation,Pos,Age,Born,Season,MP,...,The Best FIFA Mens Player,UEFA Best Player,UCL_MP,UCL_Gls,UCL_xG,UCL_Ast,UCL_xA,UCL_KP,UCL_GCA,UCL_SCA
0,2539,Manuel Neuer,Bayern Munich,Bundesliga,GER,GK,39,1986,2025-2026,9.0,...,0,0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
1,2650,Edin Džeko,Fiorentina,Serie A,BIH,FW,39,1986,2025-2026,10.0,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2747,Sven Ulreich,Bayern Munich,Bundesliga,GER,GK,37,1988,2025-2026,0.0,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2789,Dante,Nice,Ligue 1,BRA,DF,42,1983,2025-2026,2.0,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2845,Pascal Groß,Dortmund,Bundesliga,GER,MF,34,1991,2025-2026,9.0,...,0,0,2.0,0.0,0.0,0.0,0.2,1.0,1.0,2.0

In [30]:
print(df_historico.columns)
print(df_actual.columns)

Index(['PlayerID', 'Player', 'Squad', 'League', 'Nation', 'Pos', 'Age', 'Born',
       'Season', 'MP',
       ...
       'The Best FIFA Mens Player', 'UEFA Best Player', 'UCL_MP', 'UCL_Gls',
       'UCL_xG', 'UCL_Ast', 'UCL_xA', 'UCL_KP', 'UCL_GCA', 'UCL_SCA'],
      dtype='object', length=120)
Index(['PlayerID', 'Player', 'Squad', 'League', 'Nation', 'Pos', 'Age', 'Born',
       'Season', 'MP',
       ...
       'The Best FIFA Mens Player', 'UEFA Best Player', 'UCL_MP', 'UCL_Gls',
       'UCL_xG', 'UCL_Ast', 'UCL_xA', 'UCL_KP', 'UCL_GCA', 'UCL_SCA'],
      dtype='object', length=120)

In [ ]:
df_completo = pd.concat([df_historico, df_actual], ignore_index=True)
print(f"Concatenación exitosa. Filas totales: {len(df_completo)}")
df_completo.dr
df_completo.to_csv('../data/raw/Completed_data.csv')

Concatenación exitosa. Filas totales: 94899